# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4ba6efb54b2884dcc6600e00ac98b26035487882eeffd64453a483df965678133fb6f5175bafed490a26f0b04a59d88cdfb3b2c8631c0c4f44ed61b58387fdb

test:
  secret_key_base: 5b967d33b3bd5cced8a9200e474f213ac7239f76b14e659999c8a13dba9e4a8179e983b125d9e1071d76d7dadbf07a83473b7303a079c23a2ceee11a5ef48a02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
